experiment_name: 'seed2024'

seed: 2024
num_epochs: 100
batch_size: 340
log_iterations: 200
patience: 60
min_train_acc: 99.6
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
#train_embeddings: 'data_files/deeploc_our_train_embeddings.h5'
#val_embeddings: 'data_files/deeploc_our_val_embeddings.h5'
#test_embeddings: 'data_files/deeploc_test_embeddings.h5'

#train_embeddings: 'data_files/deeploc_our_train_set.h5'
#val_embeddings: 'data_files/deeploc_our_val_set.h5'
#test_embeddings: 'data_files/deeploc_test_set.h5'
train_embeddings: 'data_files/embeddings/deeploc_train_set_embeddings.h5'
val_embeddings: 'data_files/embeddings/deeploc_our_val_embeddings.h5'
test_embeddings: 'data_files/embeddings/deeploc_test_set_embeddings.h5'

train_remapping: 'data_files/1000length/deeploc_our_train_set.fasta'
val_remapping: 'data_files/1000length/deeploc_our_val_set.fasta'
test_remapping: 'data_files/1000length/deeploc_test_set.fasta'

key_format: fasta_descriptor

#key_format: hash

# continue to train
#checkpoint: 'runs/SubLoc02_07'

# Model parameters
model_type: 'SubLoc02'
model_parameters:
  dropout: 0.25
#  kernel_size: 9
  output_dim: 10
