output_files_name: 'a_test'
#seed: 1234

log_iterations: 100
n_draws: 200
batch_size: 200
checkpoints_list:
  - runs/SubLoc02_06


#embeddings: 'data_files/setHARD.h5'
#remapping: 'data_files/setHARD.fasta'

embeddings: 'data_files/deeploc_test_set.h5'
remapping: 'data_files/deeploc_test_set.fasta'


key_format: hash

